baseurl = "/"
languageCode = "en-us"
title = "He Is Better"

[params]
	verse = "For what does it profit a man to gain the whole world and forfeit his soul?"
	reference = "Mark 8:36"


[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 5

[[menu.main]]
    name = "About"
    url  = "about"
    weight = 0